### ISSUE TITLE
Suggestion - Action key toggle

### ISSUE THREAD

**Issue by IgnaceBleukx** [codecat/tm-dashboard#64] opened 2022-11-24 20:42 UTC
A nice feature to have is a toggle indicator indicating whether an action key is active or not.
For me (a beginner), it is sometimes hard to remember if I toggled on my action keys or not.

**Comment by codecat** [comment] 2022-11-25 12:51
Duplicate of #51

**Closed** 2022-11-25 12:51 UTC
