### ISSUE TITLE
bugreport: accelerating and braking are not shown correctly 

### ISSUE THREAD

**Issue by Dinoober** [codecat/tm-dashboard#85] opened 2024-12-24 02:58 UTC
In this clip I start with holding bw, but the input display shows I'm holding forwards, and both when I'm up against the wall.

Also when I'm tapping accelerate, the display shows it like I'm holding down the button, even though I'm not

https://streamable.com/u4pa36

**Comment by codecat** [comment] 2024-12-26 12:21
Duplicate of #30 - thanks for the video though, it shows the problem pretty clearly.

**Closed by codecat** 2024-12-26 12:21 UTC
